### ISSUE TITLE
Error when installing ctmatching

### ISSUE THREAD

**Issue by mchevita** [MacHu-GWU/ctmatching-project#1]
This was the error log - it seems that the "readme.rst" file name is wrong:

marcus@R2-D2-Ubuntu:~$ pip3 install ctmatching
Collecting ctmatching
  Downloading ctmatching-0.0.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-mh8s7ts7/ctmatching/setup.py", line 77, in <module>
        with open("readme.rst", "rb") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'readme.rst'

**Comment by MacHu-GWU** [comment]
You are right. 

A new version is released. Documents and continues integration is added. Please try: ``pip install --upgrade ctmatching``.
